// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903070023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Backend.Models.Import", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricId", "Year", "Period");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("Backend.Models.ImportRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportId", "RowNumber")
                        .IsUnique();

                    b.ToTable("ImportRows");
                });

            modelBuilder.Entity("Backend.Models.ImportSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("ImportSchemas");
                });

            modelBuilder.Entity("Backend.Models.ImportSchemaField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExcelColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcelColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportSchemaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricFieldId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportSchemaId");

                    b.HasIndex("MetricFieldId");

                    b.ToTable("ImportSchemaFields");
                });

            modelBuilder.Entity("Backend.Models.ImportValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportRowId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetricFieldId");

                    b.HasIndex("ImportRowId", "MetricFieldId")
                        .IsUnique();

                    b.ToTable("ImportValues");
                });

            modelBuilder.Entity("Backend.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremiumMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PremiumMethodId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Backend.Models.MetricField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRelevant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetricId", "Name")
                        .IsUnique();

                    b.ToTable("MetricFields");
                });

            modelBuilder.Entity("Backend.Models.PremiumMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PremiumPercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MethodNumber")
                        .IsUnique();

                    b.ToTable("PremiumMethods");
                });

            modelBuilder.Entity("Backend.Models.Import", b =>
                {
                    b.HasOne("Backend.Models.Metric", "Metric")
                        .WithMany("Imports")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Backend.Models.ImportRow", b =>
                {
                    b.HasOne("Backend.Models.Import", "Import")
                        .WithMany("Rows")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("Backend.Models.ImportSchema", b =>
                {
                    b.HasOne("Backend.Models.Metric", "Metric")
                        .WithMany("Schemas")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Backend.Models.ImportSchemaField", b =>
                {
                    b.HasOne("Backend.Models.ImportSchema", "ImportSchema")
                        .WithMany("Fields")
                        .HasForeignKey("ImportSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MetricField", "MetricField")
                        .WithMany("SchemaFields")
                        .HasForeignKey("MetricFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSchema");

                    b.Navigation("MetricField");
                });

            modelBuilder.Entity("Backend.Models.ImportValue", b =>
                {
                    b.HasOne("Backend.Models.ImportRow", "ImportRow")
                        .WithMany("Values")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MetricField", "MetricField")
                        .WithMany("Values")
                        .HasForeignKey("MetricFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRow");

                    b.Navigation("MetricField");
                });

            modelBuilder.Entity("Backend.Models.Metric", b =>
                {
                    b.HasOne("Backend.Models.PremiumMethod", "PremiumMethod")
                        .WithMany("Metrics")
                        .HasForeignKey("PremiumMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PremiumMethod");
                });

            modelBuilder.Entity("Backend.Models.MetricField", b =>
                {
                    b.HasOne("Backend.Models.Metric", "Metric")
                        .WithMany("Fields")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("Backend.Models.Import", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Backend.Models.ImportRow", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Backend.Models.ImportSchema", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Backend.Models.Metric", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Imports");

                    b.Navigation("Schemas");
                });

            modelBuilder.Entity("Backend.Models.MetricField", b =>
                {
                    b.Navigation("SchemaFields");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Backend.Models.PremiumMethod", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
